-- Automatically generated by packer.nvim
return {
  ["Comment.nvim"] = { commit = "e89df17", date = "1673096758" },
  ["hotpot.nvim"] = { commit = "e422268", date = "1669984174" },
  ["oxocarbon.nvim"] = { commit = "b58812c", date = "1673385359" },
  ["packer.nvim"] = { commit = "191d37b", date = "1669646807" },
  ["plenary.nvim"] = { commit = "1c7e3e6", date = "1673361461" },
}
